src/digital_library/authentication/urls.py
from django.urls import path

from .views import (
  home,
  UserLoginView,
  UserRegisterView,
  UserLogoutView,
  UserUpdateView,
)

app_name = 'account'

urlpatterns = [
  path('', home, name='home'),
  path('profile/', UserUpdateView.as_view(), name='update'),
  path('login/', UserLoginView.as_view(), name='login'),
  path('logout/', UserLogoutView.as_view(), name='logout'),
  path('register/', UserRegisterView.as_view(), name='register'),
]

src/digital_library/digital_library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('accounts/', include(('authentication.urls', 'account'), namespace='account')),
    path('', include(('library.urls', 'library'), namespace='library')),
]

src/digital_library/library/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .apis import (
  BookAdminApi,
  BookApi
)

router = DefaultRouter()
router.register(prefix='restricted/books', viewset=BookAdminApi, basename='admin-api-book')
router.register(prefix='books', viewset=BookApi, basename='api-book')

api_urlpatterns = router.urls

from .views import (
  home,
  BookListView,
  UserBookListView,
  BookDetailUpdateView,
)

urlpatterns = [
  path('', home, name='home'),
  path('api/', include(api_urlpatterns)),
  path('books/', BookListView.as_view(), name='book-list'),
  path('my-books/', UserBookListView.as_view(), name='user-book-list'),
  path('book/<pk>/', BookDetailUpdateView.as_view(), name='book-detail'),
  # 
]

src/digital_library/library/models.py
from datetime import timedelta
from django.urls import reverse
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from .constants import Languages


# Create your models here.

class Book(models.Model):
  '''Book Model'''
  
  title = models.CharField(
    max_length=60,
    db_index=True,
    help_text=_("Required. 60 characters or fewer.")
  )
  language = models.CharField(
    max_length=20,
    db_index=True,
    choices=Languages.LANGUAGE_CHOICES,
    default=Languages.ENGLISH,
    help_text=_("The language in which the book is written.")
  )
  author = models.CharField(
    max_length=40,
    db_index=True,
    help_text=_("The author of this book.")
  )
  publisher = models.CharField(
    max_length=40,
    db_index=True,
    help_text=_("The publisher by whom this book was published.")
  )
  published_date = models.DateField(
    db_index=True,
    help_text=_("The date on which this book was published by publisher.")
  )
  assigned_user = models.ForeignKey(
    to=get_user_model(),
    on_delete=models.SET_NULL,
    null=True,
    blank=True,
    verbose_name=_('assigned to'),
    help_text=_("The user whom this book was assigned.")
  )
  updated_at = models.DateTimeField(auto_now=True)
  created_at = models.DateTimeField(auto_now_add=True)
  
  
  class Meta:
    ordering = ['assigned_user']
  
  
  def __str__(self):
    return f"{self.title} - by {self.author}"
  
  
  def get_absolute_url(self):
    return reverse("library:book-detail", kwargs={"pk": self.pk})
  







# class BookLog(models.Model):
#   '''Book Log'''
  
#   MAX_ISSUE_DURATION_AT_ONCE = 3
#   MAX_SUCCESSIVE_REISSUE_LIMIT = 3
#   MIN_TIME_LIMIT_FOR_REISSUE = 1
  
#   book = models.OneToOneField(
#     to=Book,
#     on_delete=models.CASCADE,
#     help_text=_("Related book id")
#   )
#   issued_to_user = models.OneToOneField(
#     to=get_user_model(),
#     on_delete=models.SET_NULL,
#     null=True,
#     verbose_name=_('issued to'),
#     help_text=_("The user whom this book was assigned.")
#   )
#   issued_duration = models.DurationField(
#     default=timedelta(days=MAX_ISSUE_DURATION_AT_ONCE),
#     editable=False
#   )
#   issued_date = models.DateTimeField(auto_now_add=True)
#   updated_at = models.DateTimeField(auto_now=True)
  
  
#   class Meta:
#     verbose_name = _('book log entry')
#     verbose_name_plural = _('book log entries')
#     db_table = 'library_books_logs'
#     ordering = ['-issued_date']
  
#   def __str__(self):
#     return f"{self.book.title} issued by {self.issued_to_user}"
  
#   def get_book_return_datetime(self):
#     '''
#       Returns a datetime object which indicates the return datetime of the book
      
#       Returns None if error occurs
#     '''
#     try:
#       return self.issued_date + self.issued_duration
#     except Exception as e:
#       print("LIBRARY_MODELS_BOOKLOG_GET_RETURN_DATETIME_ERROR")
#       print(e)
#       return None
  
#   def is_timelimit_exceeded(self):
#     '''
#       Returns True if the time duration after issuing the book to the user, exceeded.
      
#       Returns False otherwise
      
#       Returns None if error occurs
#     '''
#     try:
#       return self.get_book_return_datetime > timezone.now()
#     except Exception as e:
#       print("LIBRARY_MODELS_BOOKLOG_IS_TIMELIMIT_EXCEEDED_ERROR")
#       print(e)
#       return None
  
#   def get_remaining_duration(self):
#     '''
#       Returns a datetime.timedelta object which shows the remaining duration since the book was issued by the user
      
#       Returns a datetime.timedelta object with value 0 if the time limit is exceeded.
      
#       Returns -1 if error occurs
#     '''
#     try:
#       if not self.is_timelimit_exceeded():
#         return self.get_book_return_datetime() - timezone.now()
#       return timedelta()
#     except Exception as e:
#       print("LIBRARY_MODELS_BOOKLOG_GET_REMAINING_DURATION_ERROR")
#       print(e)
#       return -1
  
#   def is_reissuable(self):
#     '''
#     Returns True if a user can make a successive issue of the same book
    
#     Returns False otherwise.
    
#     Returns None if error occurs.
#     '''
    
#     # 1. Check if the maximum limit for re-issue exceeded 
#     # 2. Can only re-issue if the remaining duration is not more than 24hrs. 
    
#     try:
#       return self.issued_duration < timedelta(days=self.MAX_ISSUE_DURATION_AT_ONCE*self.MAX_SUCCESSIVE_REISSUE_LIMIT) and self.get_remaining_duration() < timedelta(days=self.MIN_TIME_LIMIT_FOR_REISSUE)
#     except Exception as e:
#       print("LIBRARY_MODELS_BOOKLOG_CAN_REISSUE_ERROR")
#       print(e)
#       return None
  
#   def reissue(self):
#     '''
#     Returns True if issue_duration updated successfully
    
#     Returns False otherwise
    
#     Returns None if error occurs
#     '''
#     try:
#       if self.is_reissuable():
#         self.issued_duration += timedelta(days=self.MAX_ISSUE_DURATION_AT_ONCE)
#         return True
#       return False
#     except Exception as e:
#       print("LIBRARY_MODELS_BOOKLOG_REISSUE_ERROR")
#       print(e)
#       return None
  
#   def reissue_and_save(self):
#     '''
#     Returns True if re-issued and saved successfully
    
#     Returns False otherwise
    
#     Returns None if error occurs
#     '''
#     try:
#       if self.reissue():
#         self.save()
#         return True
#       return False
#     except Exception as e:
#       print("LIBRARY_MODELS_BOOKLOG_REISSUE_AND_SAVE_ERROR")
#       print(e)
#       return None

src/digital_library/library/forms.py
from django import forms
from .models import Book


class BookModelForm(forms.ModelForm):
  assign_to_me = forms.BooleanField(
    required=False,
    initial=True,
    widget=forms.HiddenInput()
  )
  class Meta:
    model = Book
    fields = []

src/digital_library/library/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView
from .models import Book
from .forms import BookModelForm

# Create your views here.
def home(request):
  return render(request, 'library/index.html')

class BookListView(LoginRequiredMixin, ListView):
  template_name = 'library/book_list_detail.html'
  context_object_name = 'books'
  queryset=Book.objects.all()


class UserBookListView(LoginRequiredMixin, ListView):
  template_name = 'library/book_list_detail.html'
  context_object_name = 'books'
  queryset=Book.objects.all()
  
  def get_queryset(self):
    try:
      if self.request.user.is_authenticated:
        obj = Book.objects.filter(assigned_user=self.request.user)
        return obj
    except Exception as e:
      print("LIBRARY_VIEWS_USER_BOOK_LIST_VIEW_GET_QUERYSET_ERROR")
      print(e)
      return None


class BookDetailUpdateView(LoginRequiredMixin, UpdateView):
  template_name = 'library/book_list_detail.html'
  context_object_name = 'book'
  form_class = BookModelForm
  queryset=Book.objects.all()
  
  def form_valid(self, form):
    try:
      if form.cleaned_data['assign_to_me']:
        form.instance.assigned_user = self.request.user
      else:
        form.instance.assigned_user = None
    except Exception as e:
      print("LIBRARY_VIEWS_BOOK_DETAIL_UPDATE_VIEW_FORM_VALID_ERROR")
      print(e)
    return super().form_valid(form)

src/digital_library/templates/library/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    {% comment %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    {% endcomment %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'css/library.css' %}" />
    <title>Library</title>
  </head>
  <body>
    <header>
      <h1>
        <a class="link" href="{% url 'library:home' %}">Library</a>
      </h1>
      <nav class="flexed flexed-gap-2 flexed-hr-apart flexed-wrap-revrs">
        <ul class="list">
          <li class="list-item list-item-link">
            <a class="link link-btn" href="{% url 'library:book-list' %}">All Books</a>
          </li>
          <li class="list-item list-item-link">
            <a class="link link-btn" href="{% url 'library:user-book-list' %}">My Books</a>
          </li>
          <li class="list-item list-item-link">
            <a class="link link-btn" target="blank" href="{% url 'library:api-root' %}">Books API</a>
          </li>
        </ul>
        {% if request.user.is_authenticated %}
          <div class="flexed flexed-gap">
            <a class="link link-btn" href="{% url 'account:home' %}">{{request.user}}</a>
            <a class="link link-btn link-btn-filled-danger" href="{% url 'account:logout' %}">Logout</a>
          </div>
        {% else %}
          <a class="link link-btn" href="{% url 'account:login' %}">Login</a>
        {% endif %}
      </nav>
    </header>
    <main>
      {% block content_library %}{% endblock content_library %}
    </main>
    <footer></footer>
  </body>
</html>

src/digital_library/templates/library/book_list_detail.html
{% extends 'library/base.html' %}

{% block content_library %}
<div class="library-container">
  {% if books is not None %}
    <h2>Books</h2>
    <div class="container-list">
      {% for book in books %}
        <div class="container-item">
          <a class="link link-container" href="{{book.get_absolute_url}}">
            <h3>{{book}}</h3>
            <p>Book Language - {{book.get_language_display}}</p>
            <p>
              {% if book.assigned_user %}
                {% if book.assigned_user == request.user %}
                  Read this book
                {% else %}
                  <span class="danger">Not Available</span>
                {% endif %}
              {% else %}
                <span class="success">Available</span>
              {% endif %}
            </p>
          </a>
        </div>
      {% empty %}
      <h3>No Book Found.</h3>
      {% endfor %}
    </div>
  {% endif %}
  
  
  {% if book %}
    <div class="book-container">
      <h3>About the book</h3>
      <p>
        <span class="text-bold">{{book.title}}</span>
        published on <span class="text-bold">{{book.published_date|date}}</span>
        by <span class="text-bold">{{book.author}}</span>
        in <span class="text-bold">{{book.get_language_display}}</span> language
        published in <span class="text-bold">{{book.publisher}}</span>.
      </p>
      {% if book.assigned_user %}
        {% if book.assigned_user == request.user %}
          <p>You have this book. Continue reading.</p>
          <form method="POST">
            {% csrf_token %}
            <input type="hidden" name="assign_to_me" value="False" id="id_assign_to_me">
            <input class='btn link-btn-filled-danger' type="submit" value="Return">
          </form>
        {% else %}
          <p>Someone else have this book. Check again later.</p>
        {% endif %}
      {% else %}
        {% if form %}
          <form method="POST">
            {% csrf_token %}
            {{form.assign_to_me}}
            <input class='btn link-btn-filled' type="submit" value="Issue this book">
          </form>
        {% endif %}
      {% endif %}
    </div>
  {% endif %}

</div>
{% endblock content_library %}

src/digital_library/templates/library/index.html
{% extends 'library/base.html' %} {% block content_library %}
<div class="main__head">
</div>
<div class="main__content"></div>
{% endblock content_library %}