src/digital_library/authentication/urls.py
from django.urls import path

from .views import (
  home,
  UserLoginView,
  UserRegisterView,
  UserLogoutView,
  UserUpdateView,
)

app_name = 'account'

urlpatterns = [
  path('', home, name='home'),
  path('profile/', UserUpdateView.as_view(), name='update'),
  path('login/', UserLoginView.as_view(), name='login'),
  path('logout/', UserLogoutView.as_view(), name='logout'),
  path('register/', UserRegisterView.as_view(), name='register'),
]

src/digital_library/digital_library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('accounts/', include(('authentication.urls', 'account'), namespace='account')),
    path('', include(('library.urls', 'library'), namespace='library')),
]

src/digital_library/library/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .apis import (
  BookAdminApi,
  BookApi
)

router = DefaultRouter()
router.register(prefix='restricted/books', viewset=BookAdminApi, basename='admin-api-book')
router.register(prefix='books', viewset=BookApi, basename='api-book')

api_urlpatterns = router.urls

from .views import (
  home,
  BookListView,
  UserBookListView,
  BookDetailUpdateView,
)

urlpatterns = [
  path('', home, name='home'),
  path('api/', include(api_urlpatterns)),
  path('books/', BookListView.as_view(), name='book-list'),
  path('my-books/', UserBookListView.as_view(), name='user-book-list'),
  path('book/<pk>/', BookDetailUpdateView.as_view(), name='book-detail'),
  # 
]

src/digital_library/authentication/models.py
from django.db import models

# Create your models here.

src/digital_library/authentication/forms.py
from django import forms
from django.contrib.auth import get_user_model


class CustomUserChangeForm(forms.ModelForm):
  class Meta:
    model = get_user_model()
    fields=('first_name', 'last_name', 'email')

src/digital_library/authentication/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic.edit import FormView

from django.contrib.auth.views import (
  LoginView,
  LogoutView,
)
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth import get_user_model
from .forms import CustomUserChangeForm

# Create your views here.

def home(request):
  if request.user.is_authenticated:
    return render(request, 'authentication/index.html')
  return redirect("account:login")


class UserLoginView(LoginView):
  '''Custom Login View'''
  template_name = 'authentication/auth.html'
  fields = '__all__'
  redirect_authenticated_user = True
  
  def get_success_url(self):
    return reverse('library:home')

class UserLogoutView(LogoutView):
  '''Custom Login View'''
  template_name = 'authentication/logged_out.html'
  
  def get_success_url(self):
    return reverse('library:home')


class UserRegisterView(FormView):
  template_name = 'authentication/auth.html'
  form_class = UserCreationForm
  
  def get_success_url(self):
    return reverse('library:home')
  
  def form_valid(self, form):
    try:
      print(form.cleaned_data)
      user = form.save()
      if user is not None:
        login(self.request, user)
    except Exception as e:
      print("AUTHENTICATION_VIEWS_CUSTOM_REGISTER_VIEW_FORM_VALID_ERROR")
      print(e)
    return super().form_valid(form)


class UserUpdateView(FormView):
  template_name = 'authentication/index.html'
  form_class = CustomUserChangeForm
  model = get_user_model()
  
  def post(self, request, *args, **kwargs):
    try:
      kwargs['form'] = self.form_class(data=request.POST, instance=self.model.objects.get(pk=request.user.pk))
      if kwargs['form'].is_valid():
        kwargs['form'].save()
        return redirect(self.get_success_url())
    except Exception as e:
      print("AUTHENTICATION_VIEWS_USER_UPDATE_VIEW_POST_ERROR")
      print(e)
    return render(request, self.template_name, context=kwargs)
  
  def get_success_url(self):
    return reverse('account:home')
  
  def form_valid(self, form):
    try:
      print(form.instance)
    except Exception as e:
      print("AUTHENTICATION_VIEWS_CUSTOM_REGISTER_VIEW_FORM_VALID_ERROR")
      print(e)
    return super().form_valid(form)

src/digital_library/templates/authentication/auth.html
{% extends 'authentication/base.html' %}


{% block content_auth %}
<h2>
  {% if form.password2 %}
    Create your Library Account
  {% else %}
    Sign in
  {% endif %}
</h2>

<form class="form-auth" method="POST">
  {% csrf_token %}
  
  {% if form.non_field_errors %}
    <div class="errornote">
      {% if form.non_field_errors|length == 1 %}
        {{form.non_field_errors|first}}
      {% else %}
        {% for error in form.non_field_errors %}
          {{forloop.counter}}-{{error}}
        {% endfor %}
      {% endif %}
    </div>
  {% endif %}
  
  {% if form.first_name %}
    <div class="form-row">
      <input
        class="input-auth{% if form.errors.last_name %} input-error{% endif %}"
        type="text"
        name="first_name"
        id="id_first_name"
        maxlength="30"
        minlength="3"
        placeholder="First Name"
        autocapitalize="words"
        autofocus
        autocomplete="off"
        value="{% if form.first_name.value %}{{form.first_name.value}}{% endif %}"
      />
    </div>
  {% endif %}
  
  {% if form.last_name %}
    <div class="form-row">
      <input
        class="input-auth{% if form.errors.last_name %} input-error{% endif %}"
        type="text"
        name="last_name"
        id="id_last_name"
        maxlength="30"
        minlength="3"
        placeholder="Last Name"
        autocapitalize="words"
        autocomplete="off"
        autofocus
        value="{% if form.last_name.value %}{{form.last_name.value}}{% endif %}"
      />
    </div>
  {% endif %}
  
  {% if form.email %}
    <div class="form-row">
      <input
        class="input-auth{% if form.errors.email %} input-error{% endif %}"
        type="email"
        name="email"
        id="id_email"
        maxlength="254"
        placeholder="Email"
        autocapitalize="words"
        autocomplete="off"
        autofocus
        value="{% if form.email.value %}{{form.email.value}}{% endif %}"
      />
    </div>
  {% endif %}
  
  <div class="form-row">
    <input
      class="input-auth{% if form.errors.username or form.non_field_errors %} input-error{% endif %}"
      type="text"
      name="username"
      id="id_username"
      maxlength="150"
      required
      autofocus
      placeholder="Username"
      {% if form.password2 %}
        autocomplete="off"
      {% endif %}
      value="{% if form.username.value %}{{form.username.value}}{% endif %}"
    />
    {% if form.errors.username %}
      <div class="msg error">
        <ul>
          {% for error in form.errors.username %}
            <li>
              {{error}}
            </li>
          {% endfor %}
        </ul>
      </div>
    {% elif form.username.help_text %}
      <div class="msg help">
        {{form.username.help_text|safe}}
      </div>
    {% endif %}
  </div>
  
  <div class="form-row">
    <input
      class="input-auth{% if form.errors.password or form.errors.password2 or form.non_field_errors %} input-error{% endif %}"
      type="password"
      required
      {% if form.password2 %}
        name="password1"
        id="id_password1"
        minlength="8"
        autocomplete="off"
      {% else %}
        name="password"
        id="id_password"
      {% endif %}
      placeholder="Password"
      value=""
    />
    {% if form.errors.password1 %}
      <div class="msg error">
        <ul>
          {% for error in form.errors.password1 %}
            <li>
              {{error}}
            </li>
          {% endfor %}
        </ul>
      </div>
    {% elif form.password1.help_text %}
      <div class="msg help">
        {{form.password1.help_text|safe}}
      </div>
    {% endif %}
  </div>
  
  {% if form.password2 %}
    <div class="form-row">
      <input
        class="input-auth{% if form.password2.errors %} input-error{% endif %}"
        type="password"
        name="password2"
        id="id_password2"
        required
        minlength="8"
        placeholder="Confirm Password"
        autocomplete="off"
        value=""
      />
      {% if form.errors.password2 %}
        <div class="msg error">
          <ul>
            {% for error in form.errors.password2 %}
              <li>
                {{error}}
              </li>
            {% endfor %}
          </ul>
        </div>
      {% elif form.password2.help_text %}
        <div class="msg help">
          {{form.password2.help_text|safe}}
        </div>
      {% endif %}
    </div>
  {% endif %}
  <div class="form-row flexed flexed-gap-2">
    <input type="checkbox" id="show_password" class="input-checkbox-lg">
    <label for="show_password">Show password</label>
  </div>
  
  <div class="flexed flexed-gap flexed-hr-apart flexed-revrs">
    <input class="input-submit" type="submit" value="Submit" />
    {% if form.password2 %}
      <a class="link link-btn link-btn-outlined" href="{% url 'account:login' %}">
        Sign in instead
      </a>
    {% else %}
      <a class="link link-btn link-btn-outlined" href="{% url 'account:register' %}">
        Create account
      </a>
    {% endif %}
  </div>
</form>

{% comment %} <h2>Another Form</h2>

<form method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="Submit" />
</form> {% endcomment %}

{% endblock content_auth %}

src/digital_library/templates/authentication/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <link rel="stylesheet" href="{% static 'css/authentication.css' %}">
  <script defer type="text/javascript" src="{% static 'js/authentication.js' %}"></script>
  <title>Library Authentication</title>
</head>
<body>
  <div class="container">
    <header>
      <h1>
        <a title="Go to Library" href="{% url 'library:home' %}">
          <span class="font-icon font-icon-btn link-btn-filled material-icons-round md-48">local_library</span>
        </a>
      </h1>
    </header>
    <main>
      {% block content_auth %}{% endblock content_auth %}
    </main>
    <footer>
    </footer>
  </div>
</body>
</html>

src/digital_library/templates/authentication/index.html
{% extends 'library/base.html' %}

{% block content_library %}


{% if request.user.is_authenticated %}
  <h3>Logged in as {{request.user}}</h3>
  {% if success_message %}
    <p>{{success_message}}</p>
  {% endif %}
  {% if form %}
    <form method="POST">
      {% csrf_token %}
      <p class="field-row">
        {{form.first_name.label_tag}}
        <input type="text" name="first_name" id="id_first_name" value="{{request.user.first_name}}">
      </p>
      <p class="field-row">
        {{form.last_name.label_tag}}
        <input type="text" name="last_name" id="id_last_name" value="{{request.user.last_name}}">
      </p>
      <p class="field-row">
        {{form.email.label_tag}}
        <input type="email" name="email" id="id_email" value="{{request.user.email}}">
      </p>
      <input class="btn link-btn-filled" type="submit" value="Update">
    </form>
  {% else %}
    <p class="field-row">First Name : <span class="field-value">{{request.user.first_name}}</span></p>
    <p class="field-row">Last Name : <span class="field-value">{{request.user.last_name}}</span></p>
    <p class="field-row">Email Address : <span class="field-value">{{request.user.email}}</span></p>
    <a class="link btn link-btn-filled" href="{% url 'account:update' %}">Change</a>
  {% endif %}
{% endif %}

{% endblock content_library %}

src/digital_library/templates/authentication/logged_out.html
{% extends 'library/base.html' %}


{% block content_library %}
<p>You have been logged out.</p>
<p>Try to
  <a class="link" href="{% url 'account:login' %}">Login</a>
  or
  <a class="link" href="{% url 'account:register' %}">Register</a>
</p>
{% endblock content_library %}